# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    sudo apt-get update
    sudo apt-get install sbt
  displayName: 'Install SBT'

- script: make format-check
  displayName: 'Check formatting'

- script: make compile
  displayName: 'Compile'

- script: make test
  displayName: 'Unit tests'

- script: make package
  displayName: 'Package'

- script: make it
  displayName: 'Integration test'
